global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: "api-gateway-service"
  #   static_configs:
  #     - targets: ["api-gateway-service:8080"]

  - job_name: "source-service"
    static_configs:
      - targets: ["source-service:8080"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8080"]

  # - job_name: "rabbitmq"
  #   static_configs:
  #     - targets: ["rabbitmq:15672"]

  # - job_name: "redis-cache"
  #   static_configs:
  #     - targets: ["redis_cache:6379"]
