# Build stage
FROM mcr.microsoft.com/dotnet/sdk AS build-env
WORKDIR /app

# Install Entity Framework Core tools
RUN dotnet tool install --global dotnet-ef

# Copy csproj and restore as distinct layers
# COPY *.csproj ./


# Copy everything else and build
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out


# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet
WORKDIR /app
COPY --from=build-env /app/out .

# Expose the port of your API
EXPOSE 8080

# Set the entry point for your application
ENTRYPOINT ["dotnet", "source_service.dll"]
